[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
datanexus_escrow = "gxDTeSCzk9mqiokrmTb1uNbWCjQ1rj2hsj5N65K9698"

[programs.localnet]
datanexus_escrow = "gxDTeSCzk9mqiokrmTb1uNbWCjQ1rj2hsj5N65K9698"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./platform-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
